project.clj, src/rhsm/gui/tasks/tasks.clj, src/rhsm/gui/tasks/tools.clj, src/rhsm/gui/tests/autosubscribe_tests.clj, src/rhsm/gui/tests/facts_tests.clj, src/rhsm/gui/tests/firstboot_proxy_tests.clj, src/rhsm/gui/tests/firstboot_tests.clj, src/rhsm/gui/tests/import_tests.clj, src/rhsm/gui/tests/product_status_tests.clj, src/rhsm/gui/tests/proxy_tests.clj, src/rhsm/gui/tests/register_tests.clj, src/rhsm/gui/tests/repo_tests.clj, src/rhsm/gui/tests/rhn_interop_tests.clj, src/rhsm/gui/tests/stacking_tests.clj, src/rhsm/gui/tests/subscribe_tests.clj, src/rhsm/gui/tests/subscription_status_tests.clj, src/rhsm/gui/tests/system_tests.clj, suites/sm-gui-acceptance-testng-suite.xml, suites/sm-gui-testng-suite.xml, suites/sm-gui-tier1-testng-suite.xml, suites/sm-gui-tier2-testng-suite.xml, suites/sm-gui-tier3-testng-suite.xml
=> added priority changes and firstboot proxy tests

project.clj
=> added some fix

project.clj, src/rhsm/gui/tasks/tasks.clj, src/rhsm/gui/tasks/ui.clj, src/rhsm/gui/tests/autosubscribe_tests.clj, src/rhsm/gui/tests/proxy_tests.clj, src/rhsm/gui/tests/register_tests.clj
This is the first round of fixing the register dialog as part of the mega back button set of bugs.  The auto seems to work using this, but  I haven't done a full test.  @rarebreed :  If this part works fine and doesn't need major changes go ahead and merge it to fix the other broken stuff.
=> Register Dialog Fixes

src/rhsm/gui/tests/system_tests.clj
When starting app there should not be any GTK-Warning appeared.
=> Added test that checks that no Gtk-Wanning appears on a console

src/rhsm/cli/tests/BugzillaTests.java
Automation coverage for the bugzilla's 
https://bugzilla.redhat.com/show_bug.cgi?id=1297485
https://bugzilla.redhat.com/show_bug.cgi?id=1297493
=> Verifies the /var/lib/rhsm/cache and facts file permissions 

src/rhsm/cli/tests/BugzillaTests.java
Automation coverage for the bug : https://bugzilla.redhat.com/show_bug.cgi?id=1331739
=> Verify repo-override --remove with empty string

src/rhsm/gui/tasks/tasks.clj, src/rhsm/gui/tests/import_tests.clj, src/rhsm/gui/tests/register_tests.clj, test/rhsm/gui/tests/register_test.clj, test/rhsm/gui/tests/setup_test.clj
Button "Default" provides url, port and path at the moment.
The test verifies that.
- there is a small improvement to ensure that all values are set back in rhsm.conf.
=> Updated test check_default_url

project.clj, src/rhsm/gui/tests/firstboot_proxy_tests.clj, src/rhsm/gui/tests/firstboot_tests.clj, test/rhsm/gui/tasks/tools_test.clj, test/rhsm/gui/tests/firstboot_test.clj, test/rhsm/gui/tests/register_test.clj, test/rhsm/gui/tests/setup_test.clj
Tested on my jenkins scratch.
- added support test for that behaviour
=> Make all tests related to firstboot raise an exception "SkipException" for RHEL7.2+

src/rhsm/gui/tasks/ui.clj, src/rhsm/gui/tests/facts_tests.clj, test/rhsm/gui/tests/autosubscribe_test.clj, test/rhsm/gui/tests/facts_test.clj, test/rhsm/gui/tests/register_test.clj
Two tests, each of them raises SkipException in the opposite way that the other :-)
=> verify_about_information tests for RHEL6, RHEL7

src/rhsm/gui/tests/register_tests.clj
A group of register_bad_credentials creates a lot of error messages.
Some of them were not able to close.
I have added a conditional restart of the app with force-kill?
I have added closing of registration dialog after each run of register_bad_credentials.
I have added closing of error window after ecah run of the test.
=> fixed a group of register_bad_credentials tests

src/rhsm/gui/tasks/ui.clj, src/rhsm/gui/tests/repo_tests.clj
SKU Test -> Base URL
Subscription Text -> Name
=> fixed coordinates of some fields in repo dialog

src/rhsm/cli/tests/SKULevelContentOverrideTests.java
fixed the automation failure on the skulevelcontentoverride
=> fix the skulevelcontentoverride broken code

src/rhsm/gui/tests/repo_tests.clj
If you click on "enable" checkbox to enable some repo you have to click on button "Apply".
After that all changes are applied.
=> updated test for check repo - Apply button click.

src/rhsm/gui/tests/facts_tests.clj
It is related to a combo "Releases".
=> check_available_releases works for RHEL7.3 now.

src/rhsm/gui/tests/facts_tests.clj
one print statement before verification of existence of certs.
=> added handy information before verifying certs.

src/rhsm/gui/tasks/tasks.clj
There were arguments with wrong order in a calling of register-dialog-sla .
=> fixed register dialog sla

src/rhsm/gui/tests/subscription_status_tests.clj, test/rhsm/gui/tests/subscription_status_test.clj
the changes do:
- throw a SkipException when no subscription is available
- new test that verifies that a dialog with an error is risen when attaching temporary subscription with future date
-
=> fixed most problems with check_message_status tests

src/rhsm/gui/tests/autosubscribe_tests.clj, test/rhsm/gui/tests/autosubscribe_test.clj, test/rhsm/gui/tests/facts_test.clj, test/rhsm/gui/tests/register_test.clj, test/rhsm/gui/tests/repo_test.clj, test/rhsm/gui/tests/setup_test.clj, test/rhsm/gui/tests/subscribe_test.clj
- I have used write-facts test to set a fact is_guest to false before simple_autosubscribe test is run.
- I have added clear of that fact to an original value at the end of this test.
=> added fact is_guest:false for simple_autosubscribe

src/rhsm/gui/tests/proxy_tests.clj, test/rhsm/gui/tests/subscribe_test.clj
For the bug I have reported yesterday.
=> added next reference to bugzilla bug

src/rhsm/gui/tests/subscription_status_tests.clj
Quantity is set to a negative number in some cases.
I have added additional expression to avoid this cases.
=> Taken into account a case when num of subscriptions is negative number.

src/rhsm/gui/tests/proxy_tests.clj, test/rhsm/gui/tests/proxy_test.clj
for location field.
None:None string appears in "Location" field in proxy dialog sometimes.
=> New proxy test

src/rhsm/gui/tests/proxy_tests.clj
I have made mismatch in proxy_test.
I have solved a conflict wrong way. That's it.
So this PR cleans mistakes I have made.
=> fixed mismatch with new proxy test.

src/rhsm/gui/tasks/ui.clj, src/rhsm/gui/tests/repo_tests.clj, test/rhsm/gui/tests/repo_test.clj
I have added test of test.
I have added test that verifies sorting of values in column "Repository ID' after I click on a label 'Repository ID'.
=> Automate bug 1370623

src/rhsm/gui/tasks/ui.clj, src/rhsm/gui/tests/subscribe_tests.clj, test/rhsm/gui/tests/subscribe_test.clj
New test, new element in the application map.
=> Automation of a bug 1378927

.gitignore, src/rhsm/gui/tasks/ui.clj, src/rhsm/gui/tests/product_status_tests.clj, suites/sm-gui-tier2-testng-suite.xml, test/rhsm/gui/tests/product_status_test.clj
data driven test for table 'My Products'.
It verifies that all headers can sort its column data.
=> My installed products sorting tests

src/rhsm/gui/tasks/tasks.clj, src/rhsm/gui/tests/base.clj, src/rhsm/gui/tests/system_tests.clj, test/rhsm/gui/tests/system_test.clj
- sub-man-gui should display an error dialog when network is down and I want to unsubscribe some subscription.
=> Automation of bug 1315591

src/rhsm/gui/tests/repo_tests.clj, test/rhsm/gui/tests/repo_test.clj
BTW: I have given wrong name to this branch.
- renamed the test 'check_repo_visible'
- added description for the test
=> Fix for check_repo_visible

src/rhsm/cli/tests/ComplianceTests.java, test/rhsm/cli/tests/compliance_tests.clj
The main purpose of this enhancement is to have a way to check that configuration is completed.
=> getter for one completed status variable

src/rhsm/errors/classification.clj, src/rhsm/errors/exceptions.clj, src/rhsm/gui/tests/register_tests.clj, test/rhsm/errors/classification_test.clj
Classification of various exceptions, messages from our test reports perspective.
Some exceptions should be rather skipped than counted as 'Test failure'.
=> Error type dispatcher

src/rhsm/cli/tests/FactsTests.java
Please review .
thanks,
Rehana
=> Automatation coverage for Bug 1367128 - [RFE] upload FQDN with facts

src/rhsm/gui/tasks/tasks.clj, test/rhsm/gui/tasks/tasks_test.clj
I have added download of screenshot into test-output directory. Reused our java code.
=> Screenshot in test output report

src/rhsm/gui/tests/register_tests.clj, test/rhsm/gui/tests/register_test.clj
I have added screenshot-on-exception into the 'setup' method of register tests.
=> Fix for simple register

src/rhsm/gui/tests/base.clj, src/rhsm/gui/tests/system_tests.clj, test/rhsm/gui/tests/base_test.clj, test/rhsm/gui/tests/system_test.clj
- the test verifies that the right error dialog appears when candlepin is down and proxy connection is used.
=> Automation of bug 1327179

src/rhsm/cli/tests/BugzillaTests.java
fixed few more failing bugzilla tests
=> fixed few more failing bugzilla tests

src/rhsm/errors/utils.clj
=> forgetten no-throw case in macro to normalize exceptions

automation.properties, src/rhsm/base/SubscriptionManagerCLITestScript.java, src/rhsm/cli/tasks/CandlepinTasks.java, src/rhsm/cli/tests/DevSKUTests.java, src/rhsm/cli/tests/DockerTests.java, src/rhsm/cli/tests/GoldenTicketTests.java, src/rhsm/cli/tests/MigrationDataTests.java, src/rhsm/gui/tasks/tasks.clj, test/rhsm/gui/tests/subscribe_test.clj
This is main purpose of that PR.
give a tool to see an actual situation in our GUI test play.
=> take-and-download-screenshot

src/rhsm/cli/tests/BugzillaTests.java
Hi ,
Please review the minor change on the method "VerifyEmptyRepoOverrideRemove_Test".
thanks,
Rehana
=> Updated expected result of  VerifyEmptyRepoOverrideRemove_Test

src/rhsm/cli/tests/BugzillaTests.java
=> Fix for contentavailabilty _test

src/rhsm/cli/tests/BugzillaTests.java
Should fix the last failing test
=> increasing sleep time after restarting tomcat

automation.properties, project.clj, src/rhsm/base/SubscriptionManagerCLITestScript.java, src/rhsm/cli/tasks/CandlepinTasks.java, src/rhsm/cli/tasks/SubscriptionManagerTasks.java, src/rhsm/cli/tests/BugzillaTests.java, src/rhsm/cli/tests/CRLTests.java, src/rhsm/cli/tests/ConfigTests.java, src/rhsm/cli/tests/DevSKUTests.java, src/rhsm/cli/tests/ExpirationTests.java, src/rhsm/cli/tests/GeneralTests.java, src/rhsm/cli/tests/InteroperabilityTests.java, src/rhsm/cli/tests/MigrationDataTests.java, src/rhsm/cli/tests/MigrationTests.java, src/rhsm/cli/tests/RHELPersonalTests.java, src/rhsm/cli/tests/RefreshTests.java, src/rhsm/cli/tests/ReposTests.java, src/rhsm/cli/tests/SELinuxTests.java, src/rhsm/cli/tests/SpellCheckTests.java
rhsm-qe uses new version of ssh-tools (upgraded to use sshj instead of trilead library)
=> Upgrade for a new version of ssh tools

src/rhsm/cli/tests/GoldenTicketTests.java
fix for testRepoOverridePreference test
=> fix for testRepoOverridePreference test

src/rhsm/cli/tests/FactsTests.java
Hi John, 
I have updated the test to check the presence of new fact "proc_stat.btime" in the facts --list and verified its value against the cat /proc/stat | grep btime value using awk command.
please review
thanks,
Rehana
=> updated with lastboot time changes
