src/rhsm/gui/tasks/tasks.clj
Wrapped the waittillwindowexist inside (bool ) so that it properly detected if the dialog existed or not
=> Fixed detecting of System Registration dialog

src/rhsm/gui/tasks/tasks.clj, src/rhsm/gui/tests/register_tests.clj
There is a problem with test that uses "Default" button - group activation-register. It is necessary to restart app forcing kill. Since a dialog with wrong url can be raisen.
=> added attr force-kill?

src/rhsm/gui/tasks/tasks.clj, src/rhsm/gui/tests/proxy_tests.clj
Main point of that PR is that error-dialog appears after bad_proxy test is run.
Cleaning method is sensitive for appearance of any error-dialog.
So I have a added closing of an error-dialog after bad_proxy is finished.
=> fixed bad_proxy test

src/rhsm/gui/tasks/tasks.clj
Just one line. Missing type conversion to bool in a test.
I have tested a few tests that use method close-error-dialog.
=> fixed close-error-dialog method

src/rhsm/gui/tests/repo_tests.clj
Added SkipException in the test for RHEL7.3. There is a problem with GTK3 event to toggle checkbox. This checkbox is important for this test.
=> test enable_repo_remove_all_overrides is skipped for RHEL7.3

src/rhsm/gui/tasks/tools.clj
It is related to a method tools/get-locale-regexp.
The method is used just once, so there is no worry about regression.
Test is OK for RHEL7 environment.
=> fixed too much of backslashes in regexp

src/rhsm/gui/tests/register_tests.clj, test/rhsm/gui/tasks/tools_test.clj, test/rhsm/gui/tests/repo_test.clj, test/rhsm/gui/tests/subscribe_test.clj
It is so because data are prepared in compile time. That is why the last data pair is empty since it is created from @config variable.
=> usage of (data-driven was replaced by TestNG dataProvider for tests register_bad_credentials

src/rhsm/gui/tests/import_tests.clj, src/rhsm/gui/tests/register_tests.clj
Those commands ensure that rhsmd doesnot raise an exception when entitlement cert dir is changed.
=> selinux for cert dir change working

src/rhsm/gui/tests/autosubscribe_tests.clj, src/rhsm/gui/tests/facts_tests.clj
autosubscribe_tests suite remembers original value of "productCertDir" now.
It is used to clean up the suite.
product-default is used to find cert files in facts_tests above that "product" dir.
=> remembered original value of productCertDir and added product-default path

src/rhsm/gui/tests/subscription_status_tests.clj, test/rhsm/gui/tests/autosubscribe_test.clj
There were more than one use cases that this PR solves:
- there are less than 3 subscriptions in a system
- "All Subscriptions table" disappears after attaching one subscription even two subscriptions was available
=> fixed check_message_after_attaching.

src/rhsm/gui/tasks/test_config.clj, src/rhsm/gui/tests/proxy_tests.clj, test/rhsm/gui/tests/proxy_test.clj
I have updated test-config and proxy tests that use this path.
=> proxy auth tests has had old path for a file tinyproxy.log

src/rhsm/gui/tests/proxy_tests.clj
This test is blocked by the same bugzilla bugs as a test "check_proxy_blank_credentials".
=> added blockedByBug for test_proxy_with_blank_location

src/rhsm/gui/tests/system_tests.clj, test/rhsm/gui/tests/system_test.clj
I have added a test for 'subscription-manager-gui'.
It verifies that no traceback appears in "gnome-terminal" after I pressed <ctrl-c>.
The application is started in the terminal.
=> Test for <ctrl-c> pressed in a terminal with 'subscription-manager-gui' running

src/rhsm/gui/tasks/tasks.clj, src/rhsm/gui/tests/repo_tests.clj, test/rhsm/gui/tasks/tasks_test.clj
I have added a function 'take-screenshot'.
I have added macro 'verify-or-take-screenshot'
i have switched 'verify' to 'verify-or-take-screenshot' in one repos test.
=> Fix for enable repo remove all overrides

src/rhsm/gui/tests/autosubscribe_tests.clj
The test will be skipped the same way as cli tests do.
=> SkipException when complytests are not properly initialized

src/rhsm/gui/tests/repo_tests.clj, test/rhsm/gui/tests/repo_test.clj
- there are exceptions risen from '(finally ...' in our tests.
- the exceptions are caused by (task/ui click ...). It is funny that a code suppose that some dialog window exists - ie. all tests passed. But when some problem occurs (and the dialog window is not available :-) The right exception - AssertionException is hidden by the one risen by not imporant piece of code.
Sweet hunny code.
=> Fix for check repo message unsubscribed

src/rhsm/errors/classification.clj, src/rhsm/errors/exceptions.clj
Just (gen-class) in classification.clj and exceptions.clj.
I hope it solves an error 'No implementation of method: :failure-level of protocol: #'rhsm.errors.classification/IFailureClassifier found for class: clojure.lang.PersistentArrayMap'
=> gen-class for classification and exception types

src/rhsm/gui/tests/facts_tests.clj
there is a state 'armed' in all states of the button 'Update Facts'. This state appears just right after I click on the button. The state disappears pretty quickly.
=> wait for the button 'Update Facts' shows that an action is finished

src/rhsm/gui/tests/facts_tests.clj
I have saved 5seconds propably.
I have removed (sleep 3000) (sleep 3000) by waiting till the state 'enabled' is not available for the combo 'Releases'.
=> replaced 'sleep' by waiting for being 'enabled'

src/rhsm/gui/tasks/tasks.clj, src/rhsm/gui/tests/firstboot_proxy_tests.clj, test/rhsm/gui/tasks/tasks_test.clj, test/rhsm/gui/tests/firstboot_test.clj
- new macro 'try-more'. It catches an exception for 'num' of retries.
- surrounded a verification with this macro in the test 'firstboot_enable_proxy_auth'
=> Fix for firstboot enable proxy auth

src/rhsm/gui/tasks/tasks.clj, src/rhsm/gui/tests/proxy_tests.clj, test/rhsm/gui/tests/proxy_test.clj
automated use case:
```gherkin
Given a system is unregistered
and I run subscription-manager-gui
and I click on 'Register' button
and I click on 'I would like to connect via an HTTP Proxy'
When I click on 'Use Authentication with HTTP Proxy'
and I leave fields 'user' and 'password' blank
and I click on the button 'Save'
and I click on the button 'Next' in the 'System Registration' dialog
Then I should see the message 'Proxy connection failed, please check your settings.'
and no traceback should appear in the log file.
```
=> Automation of bug 1395684

src/rhsm/gui/tests/firstboot_proxy_tests.clj, src/rhsm/gui/tests/firstboot_tests.clj, test/rhsm/gui/tests/base_test.clj, test/rhsm/gui/tests/firstboot_test.clj
It is in startup functions for 'firstboot-proxy-tests' and 'firstboot-tests'.
If firstboot does not exist there are tests that informs about that failure. 
Failure in the startup functions is caused by slow response of a test environment.
=> Start app raises skip exception instead of test failure

src/rhsm/gui/tests/register_tests.clj, src/rhsm/gui/tests/repo_tests.clj, test/rhsm/errors/classification_test.clj, test/rhsm/gui/tests/register_test.clj
It is necessary to import a code with implementation of IFailureClassifier protocol everywhere the implementation can be used.
=> Fix ifailureclassifier implementation error

src/rhsm/errors/implementations.clj, src/rhsm/errors/protocols.clj, src/rhsm/errors/utils.clj, src/rhsm/gui/tests/register_tests.clj, src/rhsm/gui/tests/repo_tests.clj, test/rhsm/errors/classification_test.clj
There was interesting problem such 'No method found for implementation IFailureClassifier for Exception. It was interesting that 'lein quickie' does not raise this error. Just 'lein testng' does that.
It was caused by that clojure does not initialize protocol for that. 
It is necessary to import a code with implementation of the protocol at the beginning of code execution. It is my early understanding of that story.
So I have splitted the files for this story into:
- errors/protocols.clj
- errors/implementations.clj
- errors/utils.clj
I am getting the right habbit with naming of source files and splitting into the right parts.
=> Rewrite of failure classification

src/rhsm/gui/tests/firstboot_tests.clj
Really small step for a programmer a huge step for our TestNG machinery.
=> fixed expected exitcode for a verification tha firstboot exists

src/rhsm/gui/tests/system_tests.clj, test/rhsm/gui/tests/system_test.clj
```gherkin
Given a 'subscription-manager-gui' is run
When I click on 'Online Documentation' in 'Help' menu
Then I should see 'firefox' app with a page
'Product Documentation for RedHat Subscription Management' openned
```
=> Automation of bug 1401108

src/rhsm/gui/tests/facts_tests.clj, test/rhsm/testng_test.clj
It was caused such that there was a value of a combo 'release' from previous test at display. And the value prohibited ldtp to read actual dialog. The actual dialog was 'facts'.
=> fixed a problem with a test 'verify_update_facts'

src/rhsm/gui/tests/subscribe_tests.clj, test/rhsm/gui/tests/subscribe_test.clj, test/rhsm/testng_test.clj
a little improvement for subscribe tests. BeforeClass method raised an error 'a system is already registered'.
=> Fix a test check unlimited quantities

src/rhsm/cli/tests/FactsTests.java
Hi john,
I have automated the bug Bug 1527727 - [RFE] Subscription-manager should report uptime or last booted time as a system fact .
Please review.
thanks,
Rehana
=> Verify uptime fact collection

src/rhsm/cli/tests/ProxyTests.java
Activationkey tests worked fine after redeploying the candlepin, so didnot touch them , will wait for one more tier3 run .
Proxy tests were failing due to this bug 1570558,so logged and blocked the test with that bug
=> blocking the test by bug 1570558
